version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_PLAYLIST=${YOUTUBE_PLAYLIST}
      - YTDL_SERVER_ENVIRON=${YTDL_SERVER_ENVIRON}
    command:
      uvicorn main:app --port 8000 --host 0.0.0.0